proxy:
  build: proxy
  container_name: proxyfier
  ports:
  - 3128
  - 3129
  - 3130
  net: host
  privileged: true
#worker:
#  build: worker
#  container_name: worker
#  command: /bin/bash -c 'while true;do curl google.fr -v ;sleep 1;done'
dns:
  build: dns
  net: host
  container_name: dns

